// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keyboard} from '../models';
import {context} from '../models';

export function AddKeyBindings(arg1:keyboard.KeyboardType):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
