// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKeyBindings(arg1) {
  return window['go']['keyboard']['Application']['AddKeyBindings'](arg1);
}

export function SetContext(arg1) {
  return window['go']['keyboard']['Application']['SetContext'](arg1);
}
